import type { Cell, Instance } from '../store/useStore';

/** Snap a value to the nearest grid multiple, eliminating floating-point noise */
const snapToGrid = (val: number, gridSize: number): number => {
  const snapped = Math.round(val / gridSize) * gridSize;
  // Round to reasonable decimal places to eliminate floating point noise
  const decimals = Math.max(0, -Math.floor(Math.log10(gridSize))) + 1;
  return parseFloat(snapped.toFixed(decimals));
};

export const generateSkillCode = (
  topLibName: string,
  topCellName: string,
  topWidth: number, 
  topHeight: number, 
  masterCells: Record<string, Cell>, 
  instances: Instance[],
  gridSize: number
): string => {
  const snap = (v: number) => snapToGrid(v, gridSize);

  // Snap top cell dimensions to grid
  const snapTopW = snap(topWidth);
  const snapTopH = snap(topHeight);
  const snapHalfW = snap(topWidth / 2);
  const snapHalfH = snap(topHeight / 2);

  let code = `; =============================================================\n`;
  code += `; SKILL Layout Floorplan\n`;
  code += `; Generated by Top-Down Floorplanner\n`;
  code += `; Top Cell : ${topLibName}/${topCellName}\n`;
  code += `; Size     : ${snapTopW} x ${snapTopH} um\n`;
  code += `; Grid     : ${gridSize} um\n`;
  code += `; =============================================================\n\n`;
  code += `let((cv master inst)\n`;

  // Step 1: Generate Master Cells
  code += `\n  ; ==========================================\n`;
  code += `  ; STEP 1: Create Master Cell Views\n`;
  code += `  ; ==========================================\n`;
  
  Object.values(masterCells).forEach(cell => {
    const snapW = snap(cell.width);
    const snapH = snap(cell.height);
    const snapCX = snap(cell.width / 2);
    const snapCY = snap(cell.height / 2);

    code += `\n  ; --- ${cell.libName}/${cell.cellName} (${snapW} x ${snapH} um) ---\n`;
    code += `  printf("Creating master: %s/%s\\n" "${cell.libName}" "${cell.cellName}")\n`;
    code += `  cv = dbOpenCellViewByType("${cell.libName}" "${cell.cellName}" "layout" "maskLayout" "w")\n`;
    code += `  dbCreateRect(cv list("prBoundary" "boundary") list(0:0 ${snapW}:${snapH}))\n`;
    code += `  dbCreateLabel(cv list("instance" "drawing") ${snapCX}:${snapCY} "${cell.cellName}" "centerCenter" "R0" "roman" ${snap(snapH * 0.1)})\n`;
    code += `  dbSave(cv)\n`;
    code += `  dbClose(cv)\n`;
  });

  // Step 2: Assemble Top Cell
  code += `\n  ; ==========================================\n`;
  code += `  ; STEP 2: Assemble ${topCellName}\n`;
  code += `  ; ==========================================\n`;
  code += `  printf("Assembling top cell: %s/%s\\n" "${topLibName}" "${topCellName}")\n`;
  code += `  cv = dbOpenCellViewByType("${topLibName}" "${topCellName}" "layout" "maskLayout" "w")\n\n`;

  // Top Cell boundary (prBoundary on the correct layer for Cadence)
  code += `  ; Chip boundary (origin at center, matching floorplanner coordinates)\n`;
  code += `  dbCreateRect(cv list("prBoundary" "boundary") list(${-snapHalfW}:${-snapHalfH} ${snapHalfW}:${snapHalfH}))\n\n`;

  if (instances.length === 0) {
    code += `  ; No instances to place\n`;
  }

  // Instantiate Sub-IPs
  instances.forEach((inst) => {
    const masterCell = masterCells[inst.cellId];
    if (!masterCell) return;

    // Snap placement coordinates to grid
    const snapX = snap(inst.x);
    const snapY = snap(inst.y);

    code += `  ; ${inst.name} <- ${masterCell.libName}/${masterCell.cellName}  @ (${snapX}, ${snapY})  [${inst.orientation}]\n`;
    code += `  master = dbOpenCellViewByType("${masterCell.libName}" "${masterCell.cellName}" "layout")\n`;
    code += `  if(master then\n`;
    code += `    inst = dbCreateInst(cv master "${inst.name}" ${snapX}:${snapY} "${inst.orientation}")\n`;
    code += `  else\n`;
    code += `    printf("ERROR: Cannot open %s/%s\\n" "${masterCell.libName}" "${masterCell.cellName}")\n`;
    code += `  )\n\n`;
  });

  code += `  dbSave(cv)\n`;
  code += `  dbClose(cv)\n`;
  code += `  printf("Done! Floorplan for ${topCellName} is ready.\\n")\n`;
  code += `)\n`;

  return code;
};

export const downloadSkillFile = (filename: string, content: string) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
