import type { Cell, Instance } from '../store/useStore';

export const generateSkillCode = (
  topWidth: number, 
  topHeight: number, 
  masterCells: Record<string, Cell>, 
  instances: Instance[]
): string => {
  let code = `; SKILL Layout Floorplan generated by Top-Down Floorplanner\n\n`;
  code += `let((cv master inst)\n`;

  // Step 1: Generate Master Cells
  code += `  ; ==========================================\n`;
  code += `  ; STEP 1: Generate Master Cells\n`;
  code += `  ; ==========================================\n`;
  
  Object.values(masterCells).forEach(cell => {
    code += `  printf("Generating Master Cell: %s/%s\\n" "${cell.libName}" "${cell.cellName}")\n`;
    code += `  cv = dbOpenCellViewByType("${cell.libName}" "${cell.cellName}" "layout" "maskLayout" "w")\n`;
    
    // Draw Bounding Box exactly at 0:0 with text drawing layer
    code += `  dbCreateRect(cv list("text" "drawing") list(0:0 ${cell.width}:${cell.height}))\n`;
    
    // Add Label at the center
    const centerX = cell.width / 2;
    const centerY = cell.height / 2;
    code += `  dbCreateLabel(cv list("text" "drawing") ${centerX}:${centerY} "${cell.cellName}" "centerCenter" "R0" "roman" 1.0)\n`;
    
    code += `  dbSave(cv)\n`;
    code += `  dbClose(cv)\n\n`;
  });

  // Step 2: Assemble top_asic
  code += `  ; ==========================================\n`;
  code += `  ; STEP 2: Assemble top_asic\n`;
  code += `  ; ==========================================\n`;
  code += `  printf("Assembling Top ASIC...\\n")\n`;
  code += `  cv = dbOpenCellViewByType("worklib" "top_asic" "layout" "maskLayout" "w")\n\n`;
  
  // Draw Top Boundary
  code += `  ; Draw top_asic boundary\n`;
  code += `  dbCreateRect(cv list("text" "drawing") list(${-topWidth / 2}:${-topHeight / 2} ${topWidth / 2}:${topHeight / 2}))\n\n`;

  if (instances.length === 0) {
    code += `  ; No instances to place\n`;
  }

  // Instantiate Sub-IPs
  instances.forEach((inst) => {
    const masterCell = masterCells[inst.cellId];
    if (!masterCell) return;

    code += `  ; Instantiate ${masterCell.cellName} at exact drawn coordinates\n`;
    code += `  master = dbOpenCellViewByType("${masterCell.libName}" "${masterCell.cellName}" "layout")\n`;
    code += `  if(master then\n`;
    code += `    inst = dbCreateInst(cv master "${inst.name}" ${inst.x}:${inst.y} "${inst.orientation}")\n`;
    code += `  else\n`;
    code += `    printf("WARNING: Could not open master cell %s/%s\\n" "${masterCell.libName}" "${masterCell.cellName}")\n`;
    code += `  )\n\n`;
  });

  code += `  dbSave(cv)\n`;
  code += `  dbClose(cv)\n`;
  code += `  printf("Successfully completed top_asic generation!\\n")\n`;
  code += `)\n`;

  return code;
};

export const downloadSkillFile = (filename: string, content: string) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
